on:
  push:
    branches: main
  pull_request:
    branches: main

  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12 #install the python needed
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        run: |
          python main.py
